spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3300/spring_dungi
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# redis 설정
redis:
  port: 6300
  host: localhost
  lettuce:
    pool:
      max-idle: 8
      min-idle: 2
      max-active: 8

# file 설정
file:
  upload:
    path: /src/main/resources/static/
  down:
    path: http://localhost:9002/static/

