spring:
  # 데이터베이스 설정
  datasource:
    source:
      jdbc-url: jdbc:mysql://localhost:3300/spring_dungi
      username: root
      password: ENC(MKcemwLpfYeOL+VwyFG48HMhSOUdhSn9)
      driver-class-name: com.mysql.jdbc.Driver
    replica:
      jdbc-url: jdbc:mysql://localhost:3301/spring_dungi
      username: root
      password: ENC(uYPzCJbPjhvNmUQE5WODAm9YULJkkKPs)
      driver-class-name: com.mysql.jdbc.Driver

  # jpa 설정
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# redis 설정
redis:
  port: 6300
  host: localhost
  password: ENC(vtjQc5k6ostA1TjT2QzQBE4yHnwl6EsI)
  lettuce:
    pool:
      max-idle: 8
      min-idle: 2
      max-active: 8

# file 설정
file:
  upload:
    path: src/main/resources/static/
  down:
    path: http://localhost:9002/static/

