server:
  port: 10001

spring:
  application:
    name: BATCH

  # 프로필 설정
  profiles:
    active: local
    include:
      - core

  # batch 설정
  batch:
    initialize-schema: always

# jasypt 설정
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}