# local file 설정
file:
  upload:
    path: images/
  down:
    path: http://localhost:9002/static/

# AWS S3 설정
cloud:
  aws:
    s3:
      bucket: diydriller-s3
    credentials:
      access-key: ENC(8/TZy+kkY/3+MyCwjWzJqsiV6Niu22QZTOwCrZx532k=)
      secret-key: ENC(ElUmdO3SowTsAOp38So3cocEdN29wqDtwR6soClLoOBhZGefhqwihaiBuOewLzY/tSkuZkiAz0s=)
    region:
      static: ap-northeast-2
    stack:
      auto: false