# aws parameter store 설정
aws:
  paramstore:
    enabled: true
    prefix: /diydriller
    profileSeparator: _
    name: dungi

spring:
  config:
    import: 'aws-parameterstore:'

  # 요청 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # mysql 연결 설정
  datasource:
    source:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10

  # jpa 설정
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect

# redis 연결 설정
redis:
  port: 6379
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  lettuce:
    pool:
      max-idle: 8
      min-idle: 2
      max-active: 8


# aws 설정
message:
  kind: sqs

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_ACCESS_KEY_SECRET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    # s3 연결 설정
    s3:
      bucket: diydriller-s3
    # sqs 연결 설정
    sqs:
      queue:
        url: ${AWS_SQS_URL}

# s3 설정
file:
  kind: s3

# 데이터베이스 replication 유무 설정
database:
  replication: false