aws:
  paramstore:
    enabled: true
    prefix: /diydriller
    profileSeparator: _
    name: dungi

spring:
  # aws 설정
  config:
    import: 'aws-parameterstore:'

  # 데이터베이스 설정
  datasource:
    source:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10

  # jpa 설정
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

# redis 설정
redis:
  port: 6379
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  lettuce:
    pool:
      max-idle: 8
      min-idle: 2
      max-active: 8


# AWS S3 설정
cloud:
  aws:
    s3:
      bucket: diydriller-s3
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_ACCESS_KEY_SECRET}
    region:
      static: ap-northeast-2
    stack:
      auto: false