# 서버 설정
server:
  port: 9002

spring:
  application:
    name: API

  # 프로필 설정
  profiles:
    active: prod
    include:
    - core

  # 요청 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # aws 설정
  config:
    import: 'aws-parameterstore:'

aws:
  paramstore:
    enabled: true
    prefix: /diydriller
    profileSeparator: _
    name: dungi

# jwt 설정
jwt:
  secret: ${JWT_SECRET}

# jasypt 설정
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
