# 서버 설정
server:
  port: 8080

spring:
  application:
    name: API

  # 프로필 설정
  profiles:
    active: prod
    include:
    - core

  # 요청 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# jwt 설정
jwt:
  secret:
